app/module_settings/models.py
from database import db

from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.sql import func

class Setting(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), unique=True, nullable=False)
    value = db.Column(db.String(100), nullable=False)
    permission = db.Column(db.Integer, nullable=False)  

    def __repr__(self):
      return f'<Setting {self.name}: {self.value}>'





def getSettingElseCreate(name, default_value, permission = 3):
  response = Setting.query.filter_by(name=name).first()
  if response is not None:
    return response.value
  else:
    db.session.add(
      Setting(
        name = name,
        value = str(default_value),
        permission = permission,
      )
    ) 
    db.session.commit()
    return default_value

app/module_settings/__init__.py
from flask import Blueprint
import logging

logger = logging.getLogger(__name__)


blueprint = Blueprint('settings', __name__, template_folder='templates')

from . import routes, models

app/module_settings/routes.py
from flask import Blueprint, render_template, Flask, request, jsonify, redirect, url_for, session, flash
from module_users.datahandler import User
from module_users.users import getSessionUser
from module_teams.models import Team
from flask_socketio import emit

from . import blueprint, logger
from .models import db, Setting
from database import socketio


@blueprint.route('/', methods=['GET'])
def overviewSettings():
    if session.get('permission', 0) >= 3:
        try:
            settings = Setting.query.all()
        except Exception as e:
            print(e)
        return render_template('settings/overviewSettings.html', settings=settings)
    else:
        return redirect(url_for('users.login'))


@blueprint.route('/updateSetting', methods=['POST','GET'])
def updateSetting():
    if request.method == 'POST':
        response = {}
        response['success'] = False
        if session.get('permission', 0) >= 2:
            form = request.form
            name = form.get("name",None)
            value = form.get("value",None)    
            if((name != None) & (value != None)):
                setting = Setting.query.filter_by(name=name).first()
                
                if session.get('permission', 0) >= setting.permission:
                    setting.value = value
                    db.session.commit()
                    response['success'] = True

                response['setting'] = {
                    'id' : setting.id,
                    'name' : setting.name,
                    'value' : setting.value,
                    'permission' : setting.permission,
                }
            emit('newData', broadcast=True, namespace='/')
    logger.debug(response)
    return redirect(url_for('settings.overviewSettings'))
        

app/module_settings/templates/settings/overviewSettings.html
{% extends "layout.html" %}

{% block title %}Einstellungen{% endblock %}

{% block content %}

<div class='container'>
    <div class='card'>
        <div class='card-header'>
            <h1>Einstellungen</h1>
        </div>
        <div class='card-body'>
            <p>
                <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Wert</th>
                        <th scope="col">Permission</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for setting in settings %}
                    <tr class="SettingRow" id="{{setting['id']}}">
                        <form action="{{ url_for('settings.updateSetting') }}" method="POST">
                            <input type="hidden" id="SettingName" name="name" value="{{setting['name']}}">
                            <input type="hidden" id="SettingId" name="id" value="{{setting['id']}}">

                            <td class="id">{{setting['id']}}</td>
                            <td class="name">
                                {{setting['name']}}
                            </td>
                            <td class="value">
                                <input type="text" id="SettingValue" class="field" value="{{setting['value']}}" required placeholder="Name" name="value">
                                {{setting['value']}}
                            </td>
                            <td class="permission">{{setting['permission']}}</td>
                            <td class="buttons">
                                <input type="submit" id="updateSettingSubmit" value="Update" class="btn btn-primary btn-large btn-block">
                            </td>
                        </form>
                    </tr>
                    {% endfor %}         
                </tbody>       
            </p>
        </div>
    </div>
    <div class='card' id="EditDiv" style="visibility:collapse;">
        <div class='card-header'>
            <h1 id="groupEditTitel">Einstellung Bearbeiten</h1>
        </div>
        <div class='card-body'>
            <form action="{{ url_for('settings.updateSetting') }}" onsubmit="clearPage()" method="POST">
                <div class="itemGroupForm">
                    <input type="hidden" id="SettingId" name="id" value="-1">
                    <div class="control-group">
                        <a>Name</a><br>
                        <input type="text" id="SettingName" class="field" value="" required placeholder="Name" name="name">
                    </div>
                    <div class="control-group">
                        <a>Wert</a><br>
                        <input type="text" id="SettingValue" class="field" value="" required placeholder="Name" name="value">
                    </div><br>
                    <input type="submit" id="updateSettingSubmit" value="Create" class="btn btn-primary btn-large btn-block">
                </div>
            </form>
        </div>
    </div>

</div>


<script>

</script>


<style>
    a{
        color: inherit; /* blue colors for links too */
        text-decoration: inherit; /* no underline */
    }
</style>
{% endblock %}