app/module_main/__init__.py
from flask import Blueprint
import logging

logger = logging.getLogger(__name__)

blueprint = Blueprint('main', __name__, template_folder='templates', static_folder='static', static_url_path='/static/main',)


from . import routes

app/module_main/routes.py
from flask import Blueprint, render_template, Flask, request, jsonify, redirect, url_for, session, flash
from flask_socketio import emit, join_room, leave_room
import module_teams
import module_sales
import module_settings
from database import db, socketio
from sqlalchemy import func, text

import datetime

from . import blueprint, logger

@blueprint.route('/',methods = ['GET'])
def index():
    return render_template('main/index.html')


@blueprint.route('/getData',methods = ['GET'])
def getData():
    data = {
        'indexShowTable': False,
        'teams':[]
    }
    indexShowTable = module_settings.models.getSettingElseCreate("indexShowTable",True,permission=2)
    

    # Get Teams as list, get add names in ranking
    Team = module_teams.models.Team
    teams = db.session.query(Team)
    teamsList = {}
    for team in teams:
        teamsList[team.id] = team.name

    ## Create Ranking table
    indexTableItemId = module_settings.models.getSettingElseCreate("indexTableItemId",1,permission=3)

    data['itemName'] = db.session.query(module_sales.models.Item).filter_by(id=indexTableItemId).first().name

    Order = module_sales.models.Order
    OrderItem = module_sales.models.OrderItem
    orders = db.session.query(OrderItem,Order,func.sum(OrderItem.quantity).label('total_quantity')).filter_by(itemId=indexTableItemId).join(Order).group_by(Order.teamId).order_by(text('total_quantity DESC'))
    #logger.debug(orders.statement.columns.keys())
    #data['dev'] = orders.statement.columns.keys()
    for row in orders.all():
        data['teams'].append({
            'team': teamsList[row[1].teamId],
            'amount': row[2]
        })
    
    # Parse Setting to show Ranking Table
    if(indexShowTable.lower() in ['true', '1', 'yes']):
        data['indexShowTable'] = True
    else:
        data['indexShowTable'] = False

    return jsonify(data)



@socketio.on('ping')
def handle_ping(data):
    data["pong"] = datetime.datetime.now().timestamp()
    emit('pong', data, broadcast=False)

@socketio.on('connect')
def test_connect(auth):
    emit('my_response', {'data': 'Connected'})

@socketio.on('disconnect')
def test_disconnect():
    print('Client disconnected')

# main driver function

app/module_main/templates/main/index.html
{% extends "layout.html" %}
{% block content%}

<div class='container'>
    <div class='card' id="secretCard" style="visibility: collapse;">
        <div class='card-header'>
            <h1>Ranking</h1>
        </div>
        <div class='card-body'>
            <img id="secret-Banner" style="width: 80%;" src="/static/main/top-secret.png" ><br>
        </div>
    </div>
    <div class='card' id="rankingCard">
        <div class='card-header'>
            <h1>Ranking</h1>
        </div>
        <div class='card-body'>
            <table id="rankingTable">
            </table>            
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script type="module">
    import { socket, watchDog, wsData } from "/static/scripts/socket.js";
    wsData.device = "enddevice";
    watchDog.pingInterval = 5000;
    
    function getData() {
        fetch('{{ url_for("main.getData") }}', {
            method: 'GET',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            }

        })
            .then((response) => response.json())
            .then((json) => {
                let data = json;
                console.debug(data);

                let tableRef = document.getElementById("rankingTable");
                tableRef.innerHTML = "";

                if(data.indexShowTable){
                    $('#secretCard').css('visibility', 'collapse');
                    $('#secretCard').height('0px');
                    $('#rankingCard').css('visibility', 'visible');

                    for (let team  in data.teams) {
                        let newRow = tableRef.insertRow(-1);
                        let nameCell = newRow.insertCell(0);
                        let amountCell = newRow.insertCell(1);
                        let bierCell = newRow.insertCell(2);
                        nameCell.setAttribute('class', 'rankingColumnTeam');
                        amountCell.setAttribute('class', 'rankingColumnAmount');
                        bierCell.setAttribute('class', 'rankingColumnBier');
                        nameCell.innerHTML = "<strong>" + data.teams[team].team + "</strong>";                        
                        amountCell.innerHTML = data.teams[team].amount;                    
                        for(let i = 1; i <= data.teams[team].amount; i++){
                            bierCell.innerHTML += "🍺";
                        }
                    }
                }
                else{
                    $('#secretCard').css('visibility', 'visible');
                    $('#secretCard').height('auto');
                    $('#rankingCard').css('visibility', 'collapse');
                    tableRef.innerHTML = "";
                    console.debug(false);
                }
            });
    }

    getData();
    socket.on('newData',getData);

</script>

{% endblock %}

{% block style %}
<style>
</style>
{% endblock %}